repos:
  - repo: https://github.com/digitalstudium/helmfmt
    rev: v0.4.3
    hooks:
      - id: helmfmt
        files: universal-chart/.*\.(yaml|yml|tpl)$

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=universal-chart/
          - --sort-values-order=file

  - repo: local
    hooks:
      - id: sync-root-readme
        name: sync root README.md from chart README.md
        language: system
        pass_filenames: false
        entry: cp universal-chart/README.md README.md
