apiVersion: v2
name: universal-chart
description: Origo universal Helm chart for all standard Kubernetes and CRD resources
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - universal
  - origo
home: https://github.com/origo-is/universal-chart
sources:
  - https://github.com/origo-is/universal-chart
maintainers:
  - name: Origo DevOps
