apiVersion: v2
name: universal-chart
description: Origo universal Helm chart for all standard Kubernetes and CRD resources

type: application

home: https://github.com/OrigoSoftwareSolutions/universal-chart

version: 1.1.6

sources:
  - https://github.com/OrigoSoftwareSolutions/universal-chart

maintainers:
  - name: Origo SoftwareSolutions DevOps

keywords:
  - universal
  - helm
  - chart
