{{- range $name, $css := .Values.clusterSecretStores }}
  {{- if not ($css.disabled | default false) }}
---
apiVersion: {{ include "helpers.capabilities.externalSecret.apiVersion" $ }}
kind: ClusterSecretStore
metadata:
  name: {{ $css.name | default (include "helpers.app.fullname" (dict "name" $name "context" $)) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with $css.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- $annots := include "helpers.app.defaultAnnotations" $ | trim }}
    {{- if or $annots $css.annotations }}
  annotations:
      {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
      {{- with $css.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- end }}
spec:
    {{- include "helpers.tplvalues.render" (dict "value" $css.spec "context" $) | nindent 2 }}
  {{- end }}
{{- end }}
