{{- range $name, $ci := .Values.clusterIssuers }}
  {{- if not ($ci.disabled | default false) }}
---
apiVersion: {{ include "helpers.capabilities.certManager.apiVersion" $ }}
kind: ClusterIssuer
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with $ci.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- $annots := include "helpers.app.defaultAnnotations" $ | trim }}
    {{- if or $annots $ci.annotations }}
  annotations:
      {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
      {{- with $ci.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- end }}
spec:
    {{- include "helpers.tplvalues.render" (dict "value" $ci.spec "context" $) | nindent 2 }}
  {{- end }}
{{- end }}
