{{- range $name, $css := .Values.clusterSecretStores }}
{{- if not ($css.disabled | default false) }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  labels: {{- include "helpers.app.selectorLabels" $ | nindent 4 }}
  {{- with $css.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml $css.spec | nindent 2 }}
{{- end }}
{{- end }}
