{{- range $name, $ces := .Values.clusterExternalSecrets }}
  {{- if not ($ces.disabled | default false) }}
---
apiVersion: {{ include "helpers.capabilities.externalSecret.apiVersion" $ }}
kind: ClusterExternalSecret
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  labels: {{- include "helpers.app.selectorLabels" $ | nindent 4 }}
    {{- with $ces.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
    {{- toYaml $ces.spec | nindent 2 }}
  {{- end }}
{{- end }}
