{{- define "local.renderConfigMap" -}}
  {{- $v := dict -}}
  {{- if typeIs "string" .value -}}
    {{- $v = fromYaml .value -}}
  {{- else if kindIs "map" .value -}}
    {{- $v = .value -}}
  {{- end -}}
  {{- range $key, $value := $v -}}
    {{- if eq (typeOf $value) "float64" -}}
      {{- printf "\n%s: %s" $key ($value | toString | quote) -}}
    {{- else if empty $value -}}
      {{- printf "\n%s: %s" $key ("" | quote) -}}
    {{- else if kindIs "string" $value -}}
      {{- printf "\n%s: %s" $key (include "local.decode" (dict "value" $value)) -}}
    {{- else -}}
      {{- printf "\n%s: %s" $key ($value | toJson | quote) -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- define "local.decode" -}}
  {{ if hasPrefix "b64:" .value }}{{ trimPrefix "b64:" .value | b64dec | quote }}{{ else }}{{ quote .value }}{{ end }}
{{- end -}}

{{- range $cName, $val := .Values.configMaps -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $val.name | default (include "helpers.app.fullname" (dict "name" $cName "context" $)) | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
  {{- include "helpers.app.labels" $ | nindent 4 }}
  {{- with $val.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{ end }}
  {{- $defaultAnnots := include "helpers.app.defaultAnnotations" $ | trim }}
  {{- if or $val.annotations $defaultAnnots }}
  annotations:
    {{- if $val.annotations -}}
      {{- $_ := include "helpers.tplvalues.render" (dict "value" $val.annotations "context" $) }}
      {{- include "helpers.app.annotations" (dict "value" $_ "context" $) | nindent 4 -}}
    {{- else }}
      {{- if $defaultAnnots }}{{ $defaultAnnots | nindent 4 }}{{- end }}
    {{- end }}
  {{- end }}
  {{- if and $val.data $val.binaryData }}{{- fail "Cannot set both data and binaryData in single ConfigMap" }} {{- end }}
  {{- with $val.immutable }}
immutable: {{ . }}
  {{- end }}
  {{- if $val.data }}
data:
    {{- include "local.renderConfigMap" ( dict "value" $val.data "context" $ ) | trim | nindent 2 }}
  {{- else if $val.binaryData }}
binaryData:
    {{- include "local.renderConfigMap" ( dict "value" $val.binaryData "context" $ ) | trim | nindent 2 }}
  {{- end -}}
{{- end -}}
