{{- if or (not (empty .Values.envs)) (not (empty .Values.envsString)) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" "envs" "context" $) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "helpers.app.labels" $ | nindent 4 }}
  {{- $hookAnnots := include "helpers.app.defaultHookAnnotations" $ | trim }}
  {{- $defaultAnnots := include "helpers.app.defaultAnnotations" $ | trim }}
  {{- if or $hookAnnots $defaultAnnots }}
  annotations:
    {{- if $hookAnnots }}{{ $hookAnnots | nindent 4 }}{{- end }}
    {{- if $defaultAnnots }}{{ $defaultAnnots | nindent 4 }}{{- end }}
  {{- end }}
data:
  {{- $d1 := include "helpers.configmaps.renderConfigMap" (dict "value" .Values.envs) | trim }}
  {{- $d2 := include "helpers.configmaps.renderConfigMap" (dict "value" .Values.envsString) | trim }}
  {{- if $d1 }}{{ $d1 | nindent 2 }}{{- end }}
  {{- if $d2 }}{{ $d2 | nindent 2 }}{{- end }}
{{- end }}

{{- range $cName, $val := .Values.configMaps -}}
  {{- if and (not (eq $cName "envs")) (not ($val.disabled | default false)) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $cName "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with $val.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{ end }}
    {{- $hookAnnots := include "helpers.app.defaultHookAnnotations" $ | trim }}
    {{- $defaultAnnots := include "helpers.app.defaultAnnotations" $ | trim }}
    {{- if or $val.annotations $hookAnnots $defaultAnnots }}
  annotations:
      {{- if $val.annotations -}}
        {{- $_ := include "helpers.tplvalues.render" (dict "value" $val.annotations "context" $) }}
        {{- include "helpers.app.annotations" (dict "value" $_ "context" $) | nindent 4 -}}
      {{- else }}
        {{- if $hookAnnots }}{{ $hookAnnots | nindent 4 }}{{- end }}
        {{- if $defaultAnnots }}{{ $defaultAnnots | nindent 4 }}{{- end }}
      {{- end }}
    {{- end }}
    {{- if and $val.data $val.binaryData }}{{- fail "Cannot set both data and binaryData in single ConfigMap" }} {{- end }}
    {{- with $val.immutable }}
immutable: {{ . }}
    {{- end }}
    {{- if $val.data }}
data:
      {{- include "helpers.configmaps.renderConfigMap" ( dict "value" $val.data "context" $ ) | trim | nindent 2 }}
    {{- else if $val.binaryData }}
binaryData:
      {{- include "helpers.configmaps.renderConfigMap" ( dict "value" $val.binaryData "context" $ ) | trim | nindent 2 }}
    {{- end -}}
  {{- end -}}
{{- end -}}
