{{- if .Values.cronJob }}
  {{- $d := .Values.cronJob }}
  {{- $name := $d.name | default $.Release.Name | trunc 63 | trimSuffix "-" }}
  {{- $cjName := $name }}
---
apiVersion: {{ include "helpers.capabilities.cronJob.apiVersion" $ }}
kind: CronJob
metadata:
  name: {{ $cjName }}
  namespace: {{ $.Release.Namespace | quote }}
  {{- include "helpers.workload.metadata" (dict "name" $name "value" $d "context" $) | nindent 2 }}
spec:
  {{- if not (eq $d.suspend nil) }}
  suspend: {{ $d.suspend }}
  {{- end }}
  schedule: {{ include "helpers.tplvalues.render" (dict "value" $d.schedule "context" $) | quote }}
  {{- with $d.timeZone }}
  timeZone: {{ . | quote }}
  {{- end }}
  {{- $cp := $d.concurrencyPolicy }}
  {{- if $cp }}
  concurrencyPolicy: {{ $cp | quote }}
  {{- else if $d.singleOnly }}
  concurrencyPolicy: Forbid
  {{- end }}
  {{- if hasKey $d "startingDeadlineSeconds" }}
  startingDeadlineSeconds: {{ $d.startingDeadlineSeconds }}
  {{- end }}
  {{- if hasKey $d "successfulJobsHistoryLimit" }}
  successfulJobsHistoryLimit: {{ $d.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if hasKey $d "failedJobsHistoryLimit" }}
  failedJobsHistoryLimit: {{ $d.failedJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
    spec:
  {{- if hasKey $d "parallelism" }}
      parallelism: {{ $d.parallelism }}
  {{- end }}
  {{- if hasKey $d "completions" }}
      completions: {{ $d.completions }}
  {{- end }}
  {{- if hasKey $d "activeDeadlineSeconds" }}
      activeDeadlineSeconds: {{ $d.activeDeadlineSeconds }}
  {{- end }}
  {{- if hasKey $d "backoffLimit" }}
      backoffLimit: {{ $d.backoffLimit }}
  {{- end }}
  {{- if hasKey $d "ttlSecondsAfterFinished" }}
      ttlSecondsAfterFinished: {{ $d.ttlSecondsAfterFinished }}
  {{- end }}
      template:
        metadata:
  {{- $podTemplateMetadata := include "helpers.workload.podTemplateMetadata" (dict "name" $name "value" $d "context" $) | trim }}
  {{- if $podTemplateMetadata }}
          {{- $podTemplateMetadata | nindent 10 }}
  {{- else }}
          {}
  {{- end }}
        spec:
  {{- include "helpers.pod" (dict "value" $d "name" $name "context" $) | trim | nindent 10 }}
          restartPolicy: {{ $d.restartPolicy | default "Never" | quote }}
  {{- $cda := $d.commandDurationAlert }}
  {{- if ne $cda nil }}
    {{- $cdaLabels := $d.commandDurationAlertLabels | default (dict "prometheus" "k8s" "role" "alert-rules") }}
    {{- $cdaRuleLabels := $d.commandDurationAlertRuleLabels | default (dict "severity" "warning") }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cronjob-{{ $cjName }}
  labels:
    {{- include "helpers.tplvalues.render" (dict "value" $cdaLabels "context" $) | nindent 4 }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  groups:
  - name: "cronJobs_rules"
    interval: 1m
    rules:
    - alert: "cronjob-{{ $cjName }}-too-long-execution"
      expr: '((time() - kube_job_status_start_time{namespace="{{ $.Release.Namespace }}", job_name=~"{{ $cjName }}-.*"}) and kube_job_status_active{namespace="{{ $.Release.Namespace }}", job_name=~"{{ $cjName }}-.*"} == 1) > {{ $cda }}'
      for: 3m
      labels:
    {{- include "helpers.tplvalues.render" (dict "value" $cdaRuleLabels "context" $) | nindent 8 }}
      annotations:
        message: "CronJob {{ $.Release.Namespace }}/{{ $cjName }} is taking more than {{ $cda }} to complete"
  {{- end }}
{{- end }}
