{{- if .Values.cronJobs -}}
  {{- $general := $.Values.cronJobsGeneral -}}
  {{- range $name, $job := .Values.cronJobs }}
    {{- if not (.disabled | default false) }}
      {{- $cjName := include "helpers.app.fullname" (dict "name" $name "context" $) }}
---
apiVersion: {{ include "helpers.capabilities.cronJob.apiVersion" $ }}
kind: CronJob
metadata:
  name: {{ $cjName }}
  namespace: {{ $.Release.Namespace | quote }}
      {{- include "helpers.workload.metadata" (dict "name" $name "value" $job "general" $general "context" $) | nindent 2 }}
spec:
      {{- if not (eq .suspend nil) }}
  suspend: {{ .suspend }}
      {{- end }}
  schedule: {{ include "helpers.tplvalues.render" (dict "value" .schedule "context" $) | quote }}
      {{- $tz := dig "timeZone" (dig "timeZone" nil $general) $job }}
      {{- with $tz }}
  timeZone: {{ . | quote }}
      {{- end }}
      {{- $cp := dig "concurrencyPolicy" (dig "concurrencyPolicy" nil $general) $job -}}
      {{- if $cp }}
  concurrencyPolicy: {{ $cp }}
      {{- else if .singleOnly }}
  concurrencyPolicy: Forbid
      {{- end }}
      {{- $sds := dig "startingDeadlineSeconds" (dig "startingDeadlineSeconds" nil $general) $job -}}
      {{- if ne $sds nil }}
  startingDeadlineSeconds: {{ $sds }}
      {{- end }}
      {{- $sjhl := dig "successfulJobsHistoryLimit" (dig "successfulJobsHistoryLimit" nil $general) $job -}}
      {{- if ne $sjhl nil }}
  successfulJobsHistoryLimit: {{ $sjhl }}
      {{- end }}
      {{- $fjhl := dig "failedJobsHistoryLimit" (dig "failedJobsHistoryLimit" nil $general) $job -}}
      {{- if ne $fjhl nil }}
  failedJobsHistoryLimit: {{ $fjhl }}
      {{- end }}
  jobTemplate:
    spec:
      {{- $par := dig "parallelism" (dig "parallelism" nil $general) $job -}}
      {{- if ne $par nil }}
      parallelism: {{ $par }}
      {{- end }}
      {{- $comp := dig "completions" (dig "completions" nil $general) $job -}}
      {{- if ne $comp nil }}
      completions: {{ $comp }}
      {{- end }}
      {{- $ads := dig "activeDeadlineSeconds" (dig "activeDeadlineSeconds" nil $general) $job -}}
      {{- if ne $ads nil }}
      activeDeadlineSeconds: {{ $ads }}
      {{- end }}
      {{- $bol := dig "backoffLimit" (dig "backoffLimit" nil $general) $job -}}
      {{- if ne $bol nil }}
      backoffLimit: {{ $bol }}
      {{- end }}
      {{- $ttl := dig "ttlSecondsAfterFinished" (dig "ttlSecondsAfterFinished" nil $general) $job -}}
      {{- if ne $ttl nil }}
      ttlSecondsAfterFinished: {{ $ttl }}
      {{- end }}
      template:
      {{- $podTemplateMetadata := include "helpers.workload.podTemplateMetadata" (dict "name" $name "value" $job "general" $general "context" $) | trim }}
      {{- if $podTemplateMetadata }}
        metadata:
        {{- $podTemplateMetadata | nindent 10 }}
      {{- else }}
        metadata: {}
      {{- end }}
        spec:
      {{- include "helpers.pod" (dict "value" . "general" $general "name" $name "context" $) | trim | nindent 10 }}
          restartPolicy: {{ .restartPolicy | default $general.restartPolicy | default "Never" }}
      {{- $cda := dig "commandDurationAlert" (dig "commandDurationAlert" nil $general) $job }}
      {{- if ne $cda nil }}
        {{- $cdaLabels := dig "commandDurationAlertLabels" (dig "commandDurationAlertLabels" (dict "prometheus" "k8s" "role" "alert-rules") $general) $job }}
        {{- $cdaRuleLabels := dig "commandDurationAlertRuleLabels" (dig "commandDurationAlertRuleLabels" (dict "severity" "warning") $general) $job }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cronjob-{{ $cjName }}
  labels:
        {{- include "helpers.tplvalues.render" (dict "value" $cdaLabels "context" $) | nindent 4 }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  groups:
  - name: "cronJobs_rules"
    interval: 1m
    rules:
    - alert: "cronjob-{{ $cjName }}-too-long-execution"
      expr: '((time() - kube_job_status_start_time{namespace="{{ $.Release.Namespace }}", job_name=~"{{ $cjName }}-.*"}) and kube_job_status_active{namespace="{{ $.Release.Namespace }}", job_name=~"{{ $cjName }}-.*"} == 1) > {{ $cda }}'
      for: 3m
      labels:
        {{- include "helpers.tplvalues.render" (dict "value" $cdaRuleLabels "context" $) | nindent 8 }}
      annotations:
        message: "CronJob {{ $.Release.Namespace }}/{{ $cjName }} is taking more than {{ $cda }} to complete"
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
