{{- $general := $.Values.daemonSetsGeneral -}}
{{- range $name, $d := .Values.daemonSets }}
  {{- if not (.disabled | default false) }}
    {{- $merged := mustMergeOverwrite (deepCopy $general) $d }}
---
apiVersion: {{ include "helpers.capabilities.daemonSet.apiVersion" $ }}
kind: DaemonSet
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
    {{- include "helpers.workload.metadata" (dict "name" $name "value" $d "general" $general "context" $) | nindent 2 }}
spec:
    {{- $rhl := dig "revisionHistoryLimit" (dig "revisionHistoryLimit" $.Values.defaults.revisionHistoryLimit $general) $d }}
    {{- if ne $rhl nil }}
  revisionHistoryLimit: {{ $rhl | int }}
    {{- end }}
    {{- with $merged.updateStrategy }}
  updateStrategy: {{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
    {{- if ne $merged.minReadySeconds nil }}
  minReadySeconds: {{ $merged.minReadySeconds }}
    {{- end }}
  selector:
    matchLabels:
    {{- include "helpers.app.workloadSelectorLabels" (dict "name" $name "context" $) | nindent 6 }}
    {{- with .extraSelectorLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 6 }}{{- end }}
  template:
    metadata:{{- include "helpers.workload.podTemplateMetadata" (dict "name" $name "value" $d "general" $general "context" $ "selectorLabels" true "extraSelectorLabels" $d.extraSelectorLabels) | nindent 6 }}
    spec:
    {{- include "helpers.pod" (dict "value" . "general" $general "name" $name "extraLabels" .extraSelectorLabels "context" $ "autoPvcs" true) | trim | nindent 6 }}
  {{- end }}
{{- end }}
