{{- if .Values.deployment }}
  {{- $d := .Values.deployment }}
  {{- $name := $d.name | default $.Release.Name | trunc 63 | trimSuffix "-" }}
---
apiVersion: {{ include "helpers.capabilities.deployment.apiVersion" $ }}
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace | quote }}
  {{- include "helpers.workload.metadata" (dict "name" $name "value" $d "context" $) | nindent 2 }}
spec:
  replicas: {{ $d.replicas | default 1 | int }}
  {{- $rhl := $d.revisionHistoryLimit }}
  {{- if ne $rhl nil }}
  revisionHistoryLimit: {{ $rhl | int }}
  {{- end }}
  {{- with $d.strategy }}
  strategy: {{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
  {{- if $d.minReadySeconds }}
  minReadySeconds: {{ $d.minReadySeconds }}
  {{- end }}
  {{- $pds := $d.progressDeadlineSeconds }}
  {{- if ne $pds nil }}
  progressDeadlineSeconds: {{ $pds }}
  {{- end }}
  selector:
    matchLabels:
  {{- include "helpers.app.workloadSelectorLabels" (dict "name" $name "context" $) | nindent 6 }}
  {{- with $d.extraSelectorLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 6 }}{{- end }}
  template:
    metadata:
  {{- include "helpers.workload.podTemplateMetadata" (dict "name" $name "value" $d "context" $ "selectorLabels" true "extraSelectorLabels" $d.extraSelectorLabels) | nindent 6 }}
    spec:
  {{- include "helpers.pod" (dict "value" $d "name" $name "extraLabels" $d.extraSelectorLabels "context" $) | trim | nindent 6 }}
{{- end }}
