{{- range $name, $es := .Values.externalSecrets }}
  {{- if not ($es.disabled | default false) }}
---
apiVersion: {{ include "helpers.capabilities.externalSecret.apiVersion" $ }}
kind: ExternalSecret
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "helpers.app.selectorLabels" $ | nindent 4 }}
    {{- with $es.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
    {{- toYaml $es.spec | nindent 2 }}
  {{- end }}
{{- end }}
