{{- if .Values.hooks -}}
  {{- $general := $.Values.hooksGeneral -}}
  {{- $hooks := list -}}
  {{- if kindIs "string" .Values.hooks -}}
{{- $hooks = fromYaml .Values.hooks -}}
  {{- else if kindIs "map" .Values.hooks -}}
{{- $hooks = .Values.hooks -}}
  {{- end -}}
  {{- range $name, $hook := $hooks }}
    {{- if not (.disabled | default false) }}
      {{- $hookName := include "helpers.app.fullname" (dict "name" $name "context" $) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $hookName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
      {{- include "helpers.app.labels" $ | nindent 4 }}
      {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  annotations:
    "helm.sh/hook": {{ .kind | default "pre-install,pre-upgrade" | quote }}
    "helm.sh/hook-weight": {{ .weight | default "5" | quote }}
    "helm.sh/hook-delete-policy": {{ .deletePolicy | default "before-hook-creation" | quote }}
      {{- include "helpers.app.defaultAnnotations" $ | indent 4 }}
      {{- with $general.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- with .annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
spec:
      {{- if (ne .parallelism nil) }}
  parallelism: {{ .parallelism }}
      {{- else if (ne $general.parallelism nil) }}
  parallelism: {{ $general.parallelism }}
      {{- end }}
      {{- if (ne .completions nil) }}
  completions: {{ .completions }}
      {{- else if (ne $general.completions nil) }}
  completions: {{ $general.completions }}
      {{- end }}
      {{- if (ne .activeDeadlineSeconds nil) }}
  activeDeadlineSeconds: {{ .activeDeadlineSeconds }}
      {{- else if (ne $general.activeDeadlineSeconds nil) }}
  activeDeadlineSeconds: {{ $general.activeDeadlineSeconds }}
      {{- end }}
      {{- if (ne .backoffLimit nil) }}
  backoffLimit: {{ .backoffLimit }}
      {{- else if (ne $general.backoffLimit nil) }}
  backoffLimit: {{ $general.backoffLimit }}
      {{- end }}
      {{- if (ne .ttlSecondsAfterFinished nil) }}
  ttlSecondsAfterFinished: {{ .ttlSecondsAfterFinished }}
      {{- else if (ne $general.ttlSecondsAfterFinished nil) }}
  ttlSecondsAfterFinished: {{ $general.ttlSecondsAfterFinished }}
      {{- end }}
  template:
    metadata:
      name: {{ $hookName }}
      {{- if or $.Values.defaults.podLabels $general.podLabels .podLabels }}
      labels:
        {{- with $.Values.defaults.podLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
        {{- with $general.podLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
        {{- with .podLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
      {{- end }}
      {{- if or $.Values.defaults.podAnnotations $general.podAnnotations .podAnnotations }}
      annotations:
        {{- with $.Values.defaults.podAnnotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
        {{- with $general.podAnnotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
        {{- with .podAnnotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
      {{- end }}
    spec:
      {{- include "helpers.pod" (dict "value" . "general" $general "name" $name "context" $) | trim | nindent 6 }}
      restartPolicy: {{ .restartPolicy | default "Never" }}
    {{- end -}}
  {{- end -}}
{{- end -}}
