{{- if .Values.hooks -}}
  {{- $general := $.Values.hooksGeneral -}}
  {{- range $name, $hook := .Values.hooks }}
    {{- if not (.disabled | default false) }}
      {{- $hookName := include "helpers.app.fullname" (dict "name" $name "context" $) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $hookName }}
  namespace: {{ $.Release.Namespace | quote }}
      {{- include "helpers.workload.metadata" (dict "name" $name "value" $hook "general" $general "context" $ "extraAnnotations" (dict "helm.sh/hook" ($hook.kind | default "pre-install,pre-upgrade") "helm.sh/hook-weight" ($hook.weight | default "5") "helm.sh/hook-delete-policy" ($hook.deletePolicy | default "before-hook-creation"))) | nindent 2 }}
spec:
      {{- $par := dig "parallelism" (dig "parallelism" nil $general) $hook -}}
      {{- if ne $par nil }}
  parallelism: {{ $par }}
      {{- end }}
      {{- $comp := dig "completions" (dig "completions" nil $general) $hook -}}
      {{- if ne $comp nil }}
  completions: {{ $comp }}
      {{- end }}
      {{- $ads := dig "activeDeadlineSeconds" (dig "activeDeadlineSeconds" nil $general) $hook -}}
      {{- if ne $ads nil }}
  activeDeadlineSeconds: {{ $ads }}
      {{- end }}
      {{- $bol := dig "backoffLimit" (dig "backoffLimit" nil $general) $hook -}}
      {{- if ne $bol nil }}
  backoffLimit: {{ $bol }}
      {{- end }}
      {{- $ttl := dig "ttlSecondsAfterFinished" (dig "ttlSecondsAfterFinished" nil $general) $hook -}}
      {{- if ne $ttl nil }}
  ttlSecondsAfterFinished: {{ $ttl }}
      {{- end }}
  template:
    metadata:
      name: {{ $hookName }}
      {{- include "helpers.workload.podTemplateMetadata" (dict "name" $name "value" $hook "general" $general "context" $) | nindent 6 }}
    spec:
      {{- include "helpers.pod" (dict "value" . "general" $general "name" $name "context" $) | trim | nindent 6 }}
      restartPolicy: {{ .restartPolicy | default "Never" }}
    {{- end -}}
  {{- end -}}
{{- end -}}
