{{- if .Values.hpa }}
  {{- $hpa := .Values.hpa }}
  {{- $name := $hpa.name | default $.Release.Name | trunc 63 | trimSuffix "-" }}
---
apiVersion: {{ include "helpers.capabilities.hpa.apiVersion" $ }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
  {{- include "helpers.app.labels" $ | nindent 4 }}
  {{- with $hpa.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  {{- $annots := include "helpers.app.defaultAnnotations" $ | trim }}
  {{- if or $annots $hpa.annotations }}
  annotations:
    {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
    {{- with $hpa.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  {{- end }}
spec:
  {{- with $hpa.scaleTargetRef }}
  scaleTargetRef:
    apiVersion: {{ .apiVersion | default "apps/v1" }}
    kind: {{ .kind | default "Deployment" }}
    name: {{ .name | default $name }}
  {{- end }}
  minReplicas: {{ $hpa.minReplicas | default 2 | int }}
  maxReplicas: {{ $hpa.maxReplicas | default 3 | int }}
  {{- $targetCPU := $hpa.targetCPU }}
  {{- $targetMemory := $hpa.targetMemory }}
  {{- $metrics := $hpa.metrics }}
  {{- if or (not (empty $targetCPU)) (not (empty $targetMemory)) $metrics }}
  metrics:
    {{- if not (empty $targetCPU) }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $targetCPU }}
    {{- end }}
    {{- if not (empty $targetMemory) }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $targetMemory }}
    {{- end }}
    {{- with $metrics }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- with $hpa.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
