{{- range $name, $hr := .Values.httpRoutes }}
  {{- if not ($hr.disabled | default false) }}
---
apiVersion: {{ include "helpers.capabilities.gatewayApi.apiVersion" $ }}
kind: HTTPRoute
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "helpers.app.selectorLabels" $ | nindent 4 }}
    {{- with $hr.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
    {{- toYaml $hr.spec | nindent 2 }}
  {{- end }}
{{- end }}
