{{- range $name, $val := .Values.imageUpdaters }}
  {{- if not ($val.disabled | default false) }}
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ include "helpers.tplvalues.render" (dict "value" ($val.metadataNamespace | default "argocd") "context" $) | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with $val.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- $annots := include "helpers.app.defaultAnnotations" $ | trim }}
    {{- if or $annots $val.annotations }}
  annotations:
      {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
      {{- with $val.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- end }}
spec:
  applicationRefs:
    - namePattern: {{ include "helpers.tplvalues.render" (dict "value" $val.applicationName "context" $) | quote }}
      images:
    {{- range $val.images }}
        - alias: {{ .alias }}
          imageName: {{ .imageName }}
          commonUpdateSettings:
            updateStrategy: {{ .updateStrategy | default "latest" }}
      {{- with .allowTags }}
            allowTags: {{ . | quote }}
      {{- end }}
      {{- with .ignoreTags }}
            ignoreTags:
        {{- toYaml . | nindent 14 }}
      {{- end }}
      {{- if .manifestTargets }}
          manifestTargets:
        {{- toYaml .manifestTargets | nindent 12 }}
      {{- else }}
          manifestTargets:
            helm:
              name: defaultImage
              tag: defaultImageTag
      {{- end }}
    {{- end }}
    {{- with $val.writeBackConfig }}
  writeBackConfig:
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
