{{- range $name, $ap := .Values.istioAuthorizationPolicies }}
  {{- if not ($ap.disabled | default false) }}
---
apiVersion: {{ include "helpers.capabilities.istiosecurity.apiVersion" $ }}
kind: AuthorizationPolicy
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with $ap.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- $annots := include "helpers.app.defaultAnnotations" $ | trim }}
    {{- if or $annots $ap.annotations }}
  annotations:
      {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
      {{- with $ap.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- end }}
spec:
    {{- include "helpers.tplvalues.render" (dict "value" $ap.spec "context" $) | nindent 2 }}
  {{- end }}
{{- end }}
