{{- range $name, $pa := .Values.istioPeerAuthentications }}
{{- if not ($pa.disabled | default false) }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "helpers.app.selectorLabels" $ | nindent 4 }}
  {{- with $pa.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml $pa.spec | nindent 2 }}
{{- end }}
{{- end }}
