{{- range $name, $ap := .Values.istioAuthorizationPolicies }}
  {{- if not ($ap.disabled | default false) }}
---
apiVersion: {{ include "helpers.capabilities.istiosecurity.apiVersion" $ }}
kind: AuthorizationPolicy
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "helpers.app.selectorLabels" $ | nindent 4 }}
    {{- with $ap.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
    {{- toYaml $ap.spec | nindent 2 }}
  {{- end }}
{{- end }}
