{{- range $name, $pa := .Values.istioPeerAuthentications }}
  {{- if not ($pa.disabled | default false) }}
---
apiVersion: {{ include "helpers.capabilities.istiosecurity.apiVersion" $ }}
kind: PeerAuthentication
metadata:
  name: {{ $pa.name | default (include "helpers.app.fullname" (dict "name" $name "context" $)) | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with $pa.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- $annots := include "helpers.app.defaultAnnotations" $ | trim }}
    {{- if or $annots $pa.annotations }}
  annotations:
      {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
      {{- with $pa.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- end }}
spec:
    {{- include "helpers.tplvalues.render" (dict "value" $pa.spec "context" $) | nindent 2 }}
  {{- end }}
{{- end }}
