{{- if .Values.jobs -}}
  {{- $general := $.Values.jobsGeneral -}}
  {{- $jobs := list -}}
  {{- if kindIs "string" .Values.jobs -}}
{{- $jobs = fromYaml .Values.jobs -}}
  {{- else if kindIs "map" .Values.jobs -}}
{{- $jobs = .Values.jobs -}}
  {{- end -}}
  {{- range $name, $job := $jobs }}
    {{- if not (.disabled | default false) }}
      {{- $jobName := include "helpers.app.fullname" (dict "name" $name "context" $) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  namespace: {{ $.Release.Namespace | quote }}
      {{- include "helpers.workload.metadata" (dict "name" $name "value" $job "general" $general "context" $) | nindent 2 }}
spec:
      {{- $par := dig "parallelism" (dig "parallelism" nil $general) $job -}}
      {{- if ne $par nil }}
  parallelism: {{ $par }}
      {{- end }}
      {{- $comp := dig "completions" (dig "completions" nil $general) $job -}}
      {{- if ne $comp nil }}
  completions: {{ $comp }}
      {{- end }}
      {{- $ads := dig "activeDeadlineSeconds" (dig "activeDeadlineSeconds" nil $general) $job -}}
      {{- if ne $ads nil }}
  activeDeadlineSeconds: {{ $ads }}
      {{- end }}
      {{- $bol := dig "backoffLimit" (dig "backoffLimit" nil $general) $job -}}
      {{- if ne $bol nil }}
  backoffLimit: {{ $bol }}
      {{- end }}
      {{- $ttl := dig "ttlSecondsAfterFinished" (dig "ttlSecondsAfterFinished" nil $general) $job -}}
      {{- if ne $ttl nil }}
  ttlSecondsAfterFinished: {{ $ttl }}
      {{- end }}
  template:
      {{- $podTemplateMetadata := include "helpers.workload.podTemplateMetadata" (dict "name" $name "value" $job "general" $general "context" $) | trim }}
      {{- if $podTemplateMetadata }}
    metadata:
      {{- $podTemplateMetadata | nindent 6 }}
      {{- else }}
    metadata: {}
      {{- end }}
    spec:
      {{- include "helpers.pod" (dict "value" . "general" $general "name" $name "context" $) | trim | nindent 6 }}
      restartPolicy: {{ .restartPolicy | default $general.restartPolicy | default "Never" }}
      {{- $cda := dig "commandDurationAlert" (dig "commandDurationAlert" nil $general) $job }}
      {{- if ne $cda nil }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: job-{{ $jobName }}
  labels:
    prometheus: k8s
    role: alert-rules
  namespace: {{ $.Release.Namespace | quote }}
spec:
  groups:
  - name: "jobs_rules"
    interval: 1m # period check for alerts
    rules:
    - alert: "job-{{ $jobName }}-too-long-execution"
      expr: '((time() - kube_job_status_start_time{namespace="{{ $.Release.Namespace }}", job_name=~"{{ $jobName }}(-.*)?"}) and kube_job_status_active{namespace="{{ $.Release.Namespace }}", job_name=~"{{ $jobName }}(-.*)?"} == 1) > {{ $cda }}'
      for: 3m
      labels:
        severity: warning
      annotations:
        message: "Job {{ $.Release.Namespace }}/{{ $jobName }} is taking more than {{ $cda }} to complete"
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
