{{- if .Values.job }}
  {{- $d := .Values.job }}
  {{- $name := $d.name | default $.Release.Name | trunc 63 | trimSuffix "-" }}
  {{- $jobName := $name }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  namespace: {{ $.Release.Namespace | quote }}
  {{- include "helpers.workload.metadata" (dict "name" $name "value" $d "context" $) | nindent 2 }}
spec:
  {{- with $d.parallelism }}
  parallelism: {{ . }}
  {{- end }}
  {{- with $d.completions }}
  completions: {{ . }}
  {{- end }}
  {{- with $d.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ . }}
  {{- end }}
  {{- with $d.backoffLimit }}
  backoffLimit: {{ . }}
  {{- end }}
  {{- with $d.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}
  template:
    metadata:
  {{- $podTemplateMetadata := include "helpers.workload.podTemplateMetadata" (dict "name" $name "value" $d "context" $) | trim }}
  {{- if $podTemplateMetadata }}
      {{- $podTemplateMetadata | nindent 6 }}
  {{- else }}
      {}
  {{- end }}
    spec:
  {{- include "helpers.pod" (dict "value" $d "name" $name "context" $) | trim | nindent 6 }}
      restartPolicy: {{ $d.restartPolicy | default "Never" }}
  {{- $cda := $d.commandDurationAlert }}
  {{- if ne $cda nil }}
    {{- $cdaLabels := $d.commandDurationAlertLabels | default (dict "prometheus" "k8s" "role" "alert-rules") }}
    {{- $cdaRuleLabels := $d.commandDurationAlertRuleLabels | default (dict "severity" "warning") }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: job-{{ $jobName }}
  labels:
    {{- include "helpers.tplvalues.render" (dict "value" $cdaLabels "context" $) | nindent 4 }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  groups:
  - name: "jobs_rules"
    interval: 1m
    rules:
    - alert: "job-{{ $jobName }}-too-long-execution"
      expr: '((time() - kube_job_status_start_time{namespace="{{ $.Release.Namespace }}", job_name=~"{{ $jobName }}(-.*)?"}) and kube_job_status_active{namespace="{{ $.Release.Namespace }}", job_name=~"{{ $jobName }}(-.*)?"} == 1) > {{ $cda }}'
      for: 3m
      labels:
    {{- include "helpers.tplvalues.render" (dict "value" $cdaRuleLabels "context" $) | nindent 8 }}
      annotations:
        message: "Job {{ $.Release.Namespace }}/{{ $jobName }} is taking more than {{ $cda }} to complete"
  {{- end }}
{{- end }}
