{{- if .Values.jobs -}}
  {{- $general := $.Values.jobsGeneral -}}
  {{- $jobs := list -}}
  {{- if kindIs "string" .Values.jobs -}}
{{- $jobs = fromYaml .Values.jobs -}}
  {{- else if kindIs "map" .Values.jobs -}}
{{- $jobs = .Values.jobs -}}
  {{- end -}}
  {{- range $name, $job := $jobs }}
    {{- if not (.disabled | default false) }}
      {{- $jobName := include "helpers.app.fullname" (dict "name" $name "context" $) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
      {{- include "helpers.app.labels" $ | nindent 4 }}
      {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- $annots := include "helpers.app.defaultAnnotations" $ | trim }}
      {{- if or $annots $general.annotations .annotations }}
  annotations:
        {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
        {{- with $general.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
        {{- with .annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- end }}
spec:
      {{- $par := dig "parallelism" (dig "parallelism" nil $general) $job -}}
      {{- if ne $par nil }}
  parallelism: {{ $par }}
      {{- end }}
      {{- $comp := dig "completions" (dig "completions" nil $general) $job -}}
      {{- if ne $comp nil }}
  completions: {{ $comp }}
      {{- end }}
      {{- $ads := dig "activeDeadlineSeconds" (dig "activeDeadlineSeconds" nil $general) $job -}}
      {{- if ne $ads nil }}
  activeDeadlineSeconds: {{ $ads }}
      {{- end }}
      {{- $bol := dig "backoffLimit" (dig "backoffLimit" nil $general) $job -}}
      {{- if ne $bol nil }}
  backoffLimit: {{ $bol }}
      {{- end }}
      {{- $ttl := dig "ttlSecondsAfterFinished" (dig "ttlSecondsAfterFinished" nil $general) $job -}}
      {{- if ne $ttl nil }}
  ttlSecondsAfterFinished: {{ $ttl }}
      {{- end }}
  template:
      {{- $autoChecksums := include "helpers.workload.autoChecksums" (dict "value" $job "general" $general "context" $) | trim }}
      {{- if or $.Values.defaults.podLabels $general.podLabels .podLabels $.Values.defaults.podAnnotations $general.podAnnotations .podAnnotations $autoChecksums }}
    metadata:
        {{- if or $.Values.defaults.podLabels $general.podLabels .podLabels }}
      labels:
          {{- with $.Values.defaults.podLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
          {{- with $general.podLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
          {{- with .podLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
        {{- end }}
        {{- if or $.Values.defaults.podAnnotations $general.podAnnotations .podAnnotations $autoChecksums }}
      annotations:
          {{- with $.Values.defaults.podAnnotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
          {{- with $general.podAnnotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
          {{- with .podAnnotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}{{- end }}
          {{- if $autoChecksums }}{{ $autoChecksums | nindent 8 }}{{- end }}
        {{- end }}
      {{- else }}
    metadata: {}
      {{- end }}
    spec:
      {{- include "helpers.pod" (dict "value" . "general" $general "name" $name "context" $) | trim | nindent 6 }}
      restartPolicy: {{ .restartPolicy | default "Never" }}
      {{- if ne .commandDurationAlert nil }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: job-{{ $jobName }}
  labels:
    prometheus: k8s
    role: alert-rules
  namespace: {{ $.Release.Namespace | quote }}
spec:
  groups:
  - name: "jobs_rules"
    interval: 1m # period check for alerts
    rules:
    - alert: "job-{{ $jobName }}-too-long-execution"
      expr: '((time() - kube_job_status_start_time{namespace="{{ $.Release.Namespace }}", job_name=~"{{ $jobName }}(-.*)?"}) and kube_job_status_active{namespace="{{ $.Release.Namespace }}", job_name=~"{{ $jobName }}(-.*)?"} == 1) > {{ .commandDurationAlert }}'
      for: 3m
      labels:
        severity: warning
      annotations:
        message: "Job {{ $.Release.Namespace }}/{{ $jobName }} is taking more than {{ .commandDurationAlert }} to complete"
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
