{{- if .Values.job }}
  {{- $d := .Values.job }}
  {{- $name := $d.name | default $.Release.Name | trunc 63 | trimSuffix "-" }}
  {{- $jobName := $name }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  {{- include "helpers.workload.metadata" (dict "name" $name "value" $d "context" $) | nindent 2 }}
spec:
  {{- if hasKey $d "parallelism" }}
  parallelism: {{ $d.parallelism }}
  {{- end }}
  {{- if hasKey $d "completions" }}
  completions: {{ $d.completions }}
  {{- end }}
  {{- if hasKey $d "activeDeadlineSeconds" }}
  activeDeadlineSeconds: {{ $d.activeDeadlineSeconds }}
  {{- end }}
  {{- if hasKey $d "backoffLimit" }}
  backoffLimit: {{ $d.backoffLimit }}
  {{- end }}
  {{- if hasKey $d "ttlSecondsAfterFinished" }}
  ttlSecondsAfterFinished: {{ $d.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
  {{- $podTemplateMetadata := include "helpers.workload.podTemplateMetadata" (dict "name" $name "value" $d "context" $) | trim }}
  {{- if $podTemplateMetadata }}
      {{- $podTemplateMetadata | nindent 6 }}
  {{- else }}
      {}
  {{- end }}
    spec:
  {{- include "helpers.pod" (dict "value" $d "name" $name "context" $) | trim | nindent 6 }}
      restartPolicy: {{ $d.restartPolicy | default "Never" | quote }}
{{- end }}
