{{- if .Values.pdb }}
  {{- $pdb := .Values.pdb }}
  {{- $name := $pdb.name | default $.Release.Name | trunc 63 | trimSuffix "-" }}
  {{- if not (or (hasKey $pdb "minAvailable") (hasKey $pdb "maxUnavailable")) }}
    {{- fail (printf "pdb: must set either minAvailable or maxUnavailable") }}
  {{- end }}
---
apiVersion: {{ include "helpers.capabilities.pdb.apiVersion" $ }}
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
  {{- include "helpers.app.labels" $ | nindent 4 }}
  {{- with $pdb.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  {{- $annots := include "helpers.app.defaultAnnotations" $ | trim }}
  {{- if or $annots $pdb.annotations }}
  annotations:
    {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
    {{- with $pdb.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  {{- end }}
spec:
  {{- if hasKey $pdb "minAvailable" }}
  minAvailable: {{ $pdb.minAvailable }}
  {{- else if hasKey $pdb "maxUnavailable" }}
  maxUnavailable: {{ $pdb.maxUnavailable }}
  {{- end }}
  {{- with $pdb.unhealthyPodEvictionPolicy }}
    {{- if semverCompare ">=1.27-0" $.Capabilities.KubeVersion.GitVersion }}
  unhealthyPodEvictionPolicy: {{ . }}
    {{- end }}
  {{- end }}
  selector:
    matchLabels:
  {{- include "helpers.app.workloadSelectorLabels" (dict "name" $name "context" $) | nindent 6 }}
  {{- with $pdb.extraSelectorLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 6 }}{{- end -}}
{{- end }}
