{{- define "local.renderSecret" -}}
  {{- $v := dict -}}
  {{- if kindIs "string" .value -}}
    {{- $v = fromYaml .value }}
  {{- else -}}
    {{- $v = .value }}
  {{- end -}}
  {{- range $key, $value := $v -}}
    {{- if kindIs "string" $value -}}
      {{- printf "\n%s: %s" $key (include "local.encode" (dict "value" $value)) -}}
    {{- else -}}
      {{- printf "\n%s: %s" $key ($value | toJson | b64enc) -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- define "local.encode" -}}
  {{ if hasPrefix "b64:" .value }}{{ trimPrefix "b64:" .value }}{{ else }}{{ toString .value | b64enc }}{{ end }}
{{- end -}}

{{- range $sName, $val := .Values.secrets -}}
---
apiVersion: v1
kind: Secret
type: {{ $val.type | default  "Opaque" }}
metadata:
  name: {{ $val.name | default (include "helpers.app.fullname" (dict "name" $sName "context" $)) | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
  {{- include "helpers.app.labels" $ | nindent 4 }}
  {{- with $val.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{ end }}
  {{- $defaultAnnots := include "helpers.app.defaultAnnotations" $ | trim }}
  {{- if or $val.annotations $defaultAnnots $val.keepOnDelete }}
  annotations:
    {{- if $val.keepOnDelete }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- if $val.annotations -}}
      {{- $_ := include "helpers.tplvalues.render" (dict "value" $val.annotations "context" $) }}
      {{- include "helpers.app.annotations" (dict "value" $_ "context" $) | nindent 4 -}}
    {{- else }}
      {{- if $defaultAnnots }}{{ $defaultAnnots | nindent 4 }}{{- end }}
    {{- end }}
  {{- end }}
  {{- if $val.immutable }}
immutable: {{ $val.immutable }}
  {{- end }}
  {{- if $val.data }}
data:
    {{- $data := include "local.renderSecret" (dict "value" $val.data) | trim }}
    {{- if $data }}{{ $data | nindent 2 }}{{- end }}
  {{- end }}
  {{- if $val.stringData }}
stringData:
    {{- toYaml $val.stringData | nindent 2 }}
  {{- end }}
{{- end }}
