{{- range $name, $ss := .Values.secretStores }}
  {{- if not ($ss.disabled | default false) }}
---
apiVersion: {{ include "helpers.capabilities.externalSecret.apiVersion" $ }}
kind: SecretStore
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with $ss.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- $annots := include "helpers.app.defaultAnnotations" $ | trim }}
    {{- if or $annots $ss.annotations }}
  annotations:
      {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
      {{- with $ss.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- end }}
spec:
    {{- include "helpers.tplvalues.render" (dict "value" $ss.spec "context" $) | nindent 2 }}
  {{- end }}
{{- end }}
