{{- range $name, $ss := .Values.secretStores }}
  {{- if not ($ss.disabled | default false) }}
---
apiVersion: {{ include "helpers.capabilities.externalSecret.apiVersion" $ }}
kind: SecretStore
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "helpers.app.selectorLabels" $ | nindent 4 }}
    {{- with $ss.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
    {{- toYaml $ss.spec | nindent 2 }}
  {{- end }}
{{- end }}
