{{- if or (not (empty .Values.secretEnvs)) (not (empty .Values.secretEnvsString)) }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" "secret-envs" "context" $) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "helpers.app.labels" $ | nindent 4 }}
  {{- $hookAnnots := include "helpers.app.defaultHookAnnotations" $ | trim }}
  {{- $defaultAnnots := include "helpers.app.defaultAnnotations" $ | trim }}
  {{- if or $hookAnnots $defaultAnnots }}
  annotations:
    {{- if $hookAnnots }}{{ $hookAnnots | nindent 4 }}{{- end }}
    {{- if $defaultAnnots }}{{ $defaultAnnots | nindent 4 }}{{- end }}
  {{- end }}
data:
  {{- $d1 := include "helpers.secrets.render" (dict "value" .Values.secretEnvsString) | trim }}
  {{- $d2 := include "helpers.secrets.render" (dict "value" .Values.secretEnvs) | trim }}
  {{- if $d1 }}{{ $d1 | nindent 2 }}{{- end }}
  {{- if $d2 }}{{ $d2 | nindent 2 }}{{- end }}
{{- end }}

{{- range $sName, $val := .Values.secrets -}}
  {{- if and (not (eq $sName "secret-envs")) (not ($val.disabled | default false)) }}
---
apiVersion: v1
kind: Secret
type: {{ $val.type | default  "Opaque" }}
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $sName "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with $val.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{ end }}
    {{- $hookAnnots := include "helpers.app.defaultHookAnnotations" $ | trim }}
    {{- $defaultAnnots := include "helpers.app.defaultAnnotations" $ | trim }}
    {{- if or $val.annotations (or $hookAnnots (or $defaultAnnots $val.keepOnDelete)) }}
  annotations:
      {{- if $val.keepOnDelete }}
    helm.sh/resource-policy: keep
      {{- end }}
      {{- if $val.annotations -}}
        {{- $_ := include "helpers.tplvalues.render" (dict "value" $val.annotations "context" $) }}
        {{- include "helpers.app.annotations" (dict "value" $_ "context" $) | nindent 4 -}}
      {{- else }}
        {{- if $hookAnnots }}{{ $hookAnnots | nindent 4 }}{{- end }}
        {{- if $defaultAnnots }}{{ $defaultAnnots | nindent 4 }}{{- end }}
      {{- end }}
    {{- end }}
    {{- if $val.immutable }}
immutable: {{ $val.immutable }}
    {{- end }}
    {{- if $val.data }}
data:
      {{- $data := include "helpers.secrets.render" (dict "value" $val.data) | trim }}
      {{- if $data }}{{ $data | nindent 2 }}{{- end }}
    {{- end }}
    {{- if $val.stringData }}
stringData:
      {{- toYaml $val.stringData | nindent 2 }}
    {{- end }}
  {{- end }}
{{- end }}
