{{- if or (not (empty .Values.secretEnvs)) (not (empty .Values.secretEnvsString)) }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" "secret-envs" "context" $) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "helpers.app.labels" $ | nindent 4 }}
  {{- $hookAnnots := include "helpers.app.defaultHookAnnotations" $ | trim }}
  {{- if $hookAnnots }}
  annotations:{{ $hookAnnots | nindent 4 }}
  {{- end }}
data:
  {{- $d1 := include "helpers.secrets.render" (dict "value" .Values.secretEnvsString) | trim }}
  {{- $d2 := include "helpers.secrets.render" (dict "value" .Values.secretEnvs) | trim }}
  {{- if $d1 }}{{ $d1 | nindent 2 }}{{- end }}
  {{- if $d2 }}{{ $d2 | nindent 2 }}{{- end }}
{{- end }}

{{- range $sName, $val := .Values.secrets -}}
  {{- if not (eq $sName "secret-envs") }}
---
apiVersion: v1
kind: Secret
type: {{ $val.type | default  "Opaque" }}
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $sName "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with $val.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{ end }}
    {{- $hookAnnots := include "helpers.app.defaultHookAnnotations" $ | trim }}
    {{- if or $val.annotations $hookAnnots }}
  annotations:
      {{- if $val.annotations -}}
        {{- $_ := include "helpers.tplvalues.render" (dict "value" $val.annotations "context" $) }}
        {{- include "helpers.app.annotations" (dict "value" $_ "context" $) | nindent 4 -}}
      {{- else }}
      {{- $hookAnnots | nindent 4 }}
      {{- end }}
    {{- end }}
data:
    {{- $data := include "helpers.secrets.render" (dict "value" $val.data) | trim }}
    {{- if $data }}{{ $data | nindent 2 }}{{- end }}
  {{- end }}
{{- end }}

{{- range $name, $value := .Values.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "helpers.app.labels" $ | nindent 4 }}
  {{- $hookAnnots := include "helpers.app.defaultHookAnnotations" $ | trim }}
  {{- if $hookAnnots }}
  annotations:{{ $hookAnnots | nindent 4 }}
  {{- end }}
data:
  {{- $data := include "helpers.secrets.render" (dict "value" (printf ".dockerconfigjson: %v" $value)) | trim }}
  {{- if $data }}{{ $data | nindent 2 }}{{- end }}
{{- end }}
