{{- if .Values.serviceAccounts -}}
  {{- $general := $.Values.serviceAccountsGeneral -}}
  {{- $serviceAccount := list -}}
  {{- if kindIs "string" .Values.serviceAccounts -}}
{{- $serviceAccount = fromYaml .Values.serviceAccounts -}}
  {{- else if kindIs "map" .Values.serviceAccounts -}}
{{- $serviceAccount = .Values.serviceAccounts -}}
  {{- end -}}
  {{- range $name, $val := $serviceAccount }}
    {{- if not (.disabled | default false) }}
---
apiVersion: v1
kind: ServiceAccount
      {{- $annots := include "helpers.app.defaultAnnotations" $ | trim }}
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
      {{- include "helpers.app.labels" $ | nindent 4 }}
      {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- if or $annots $general.annotations .annotations }}
  annotations:
        {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
        {{- with $general.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
        {{- with .annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- end }}
      {{- if hasKey $val "automountServiceAccountToken" }}
automountServiceAccountToken: {{ $val.automountServiceAccountToken }}
      {{- else if hasKey $general "automountServiceAccountToken" }}
automountServiceAccountToken: {{ $general.automountServiceAccountToken }}
      {{- else }}
automountServiceAccountToken: false
      {{- end }}
      {{- if hasKey $val "imagePullSecrets" }}
imagePullSecrets:
        {{- toYaml $val.imagePullSecrets | nindent 2 }}
      {{- else if hasKey $general "imagePullSecrets" }}
imagePullSecrets:
        {{- toYaml $general.imagePullSecrets | nindent 2 }}
      {{- end }}
      {{- if hasKey $val "secrets" }}
secrets:
        {{- toYaml $val.secrets | nindent 2 }}
      {{- else if hasKey $general "secrets" }}
secrets:
        {{- toYaml $general.secrets | nindent 2 }}
      {{- end }}
      {{- $role := $val.role | default $general.role -}}
      {{- if $role }}
        {{- if $role.rules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $role.name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
          {{- include "helpers.app.labels" $ | nindent 4 }}
          {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
          {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
          {{- if or $annots $general.annotations .annotations }}
  annotations:
            {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
            {{- with $general.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
            {{- with .annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
          {{- end }}
rules:
          {{- include "helpers.tplvalues.render" (dict "value" $role.rules "context" $) | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $role.name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
          {{- include "helpers.app.labels" $ | nindent 4 }}
          {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
          {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
          {{- if or $annots $general.annotations .annotations }}
  annotations:
            {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
            {{- with $general.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
            {{- with .annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
          {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "helpers.app.fullname" (dict "name" $role.name "context" $) }}
subjects:
- kind: ServiceAccount
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
        {{- else }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $role.name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
          {{- include "helpers.app.labels" $ | nindent 4 }}
          {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
          {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
          {{- if or $annots $general.annotations .annotations }}
  annotations:
            {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
            {{- with $general.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
            {{- with .annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
          {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $role.name }}
subjects:
- kind: ServiceAccount
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
        {{- end }}
      {{- end }}
      {{- $cr := $val.clusterRole | default $general.clusterRole -}}
      {{- if $cr }}
          {{- if $cr.rules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $cr.name "context" $) }}
  labels:
            {{- include "helpers.app.labels" $ | nindent 4 }}
            {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
            {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
            {{- if or $annots $general.annotations .annotations }}
  annotations:
              {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
              {{- with $general.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
              {{- with .annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
            {{- end }}
rules:
            {{- include "helpers.tplvalues.render" (dict "value" $cr.rules "context" $) | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $cr.name "context" $) }}
  labels:
            {{- include "helpers.app.labels" $ | nindent 4 }}
            {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
            {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
            {{- if or $annots $general.annotations .annotations }}
  annotations:
              {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
              {{- with $general.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
              {{- with .annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
            {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "helpers.app.fullname" (dict "name" $cr.name "context" $) }}
subjects:
- kind: ServiceAccount
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
          {{- else }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $cr.name "context" $) }}
  labels:
            {{- include "helpers.app.labels" $ | nindent 4 }}
            {{- with $general.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
            {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
            {{- if or $annots $general.annotations .annotations }}
  annotations:
              {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
              {{- with $general.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
              {{- with .annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
            {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $cr.name }}
subjects:
- kind: ServiceAccount
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
          {{- end }}
      {{- end }}
    {{- end }}
  {{- end -}}
{{- end }}
