{{- range .Values.serviceAccount }}
  {{- $sa := . }}
  {{- $name := $sa.name | default $.Release.Name | trunc 63 | trimSuffix "-" }}
  {{- $annots := include "helpers.app.defaultAnnotations" $ | trim }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
  {{- include "helpers.app.labels" $ | nindent 4 }}
  {{- with $sa.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  {{- if or $annots $sa.annotations }}
  annotations:
    {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
    {{- with $sa.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  {{- end }}
automountServiceAccountToken: false
  {{- if $sa.imagePullSecrets }}
imagePullSecrets:
    {{- toYaml $sa.imagePullSecrets | nindent 2 }}
  {{- end }}
  {{- if $sa.secrets }}
secrets:
    {{- toYaml $sa.secrets | nindent 2 }}
  {{- end }}
  {{- $role := $sa.role }}
  {{- if $role }}
    {{- $roleName := "" }}
    {{- if $role.rules }}
      {{- if $role.name }}
        {{- $roleName = $role.name }}
      {{- else }}
        {{- $roleName = $name | trunc 63 | trimSuffix "-" }}
      {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $roleName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
      {{- include "helpers.app.labels" $ | nindent 4 }}
      {{- with $sa.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- if or $annots $sa.annotations }}
  annotations:
        {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
        {{- with $sa.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- end }}
rules:
      {{- include "helpers.tplvalues.render" (dict "value" $role.rules "context" $) | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $roleName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
      {{- include "helpers.app.labels" $ | nindent 4 }}
      {{- with $sa.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- if or $annots $sa.annotations }}
  annotations:
        {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
        {{- with $sa.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $roleName | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ $name }}
    namespace: {{ $.Release.Namespace | quote }}
    {{- else }}
      {{- $roleName = required "serviceAccount[].role.name is required when rules are omitted (binding to an existing Role)" $role.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $roleName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
      {{- include "helpers.app.labels" $ | nindent 4 }}
      {{- with $sa.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- if or $annots $sa.annotations }}
  annotations:
        {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
        {{- with $sa.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $roleName | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ $name }}
    namespace: {{ $.Release.Namespace | quote }}
    {{- end }}
  {{- end }}
  {{- $cr := $sa.clusterRole }}
  {{- if $cr }}
    {{- $clusterRoleName := "" }}
    {{- if $cr.rules }}
      {{- if $cr.name }}
        {{- $clusterRoleName = $cr.name }}
      {{- else }}
        {{- $clusterRoleName = printf "%s-%s" $.Release.Namespace $name | trunc 63 | trimSuffix "-" }}
      {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $clusterRoleName | quote }}
  labels:
      {{- include "helpers.app.labels" $ | nindent 4 }}
      {{- with $sa.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- if or $annots $sa.annotations }}
  annotations:
        {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
        {{- with $sa.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- end }}
rules:
      {{- include "helpers.tplvalues.render" (dict "value" $cr.rules "context" $) | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $clusterRoleName | quote }}
  labels:
      {{- include "helpers.app.labels" $ | nindent 4 }}
      {{- with $sa.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- if or $annots $sa.annotations }}
  annotations:
        {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
        {{- with $sa.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $clusterRoleName | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ $name }}
    namespace: {{ $.Release.Namespace | quote }}
    {{- else }}
      {{- $clusterRoleName = required "serviceAccount[].clusterRole.name is required when rules are omitted (binding to an existing ClusterRole)" $cr.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $clusterRoleName | quote }}
  labels:
      {{- include "helpers.app.labels" $ | nindent 4 }}
      {{- with $sa.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- if or $annots $sa.annotations }}
  annotations:
        {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
        {{- with $sa.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $clusterRoleName | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ $name }}
    namespace: {{ $.Release.Namespace | quote }}
    {{- end }}
  {{- end }}
{{- end }}
