{{- range .Values.serviceAccount }}
  {{- $sa := . }}
  {{- $name := $sa.name | default $.Release.Name | trunc 63 | trimSuffix "-" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  {{- include "helpers.workload.metadata" (dict "value" $sa "context" $) | nindent 2 }}
automountServiceAccountToken: false
  {{- if $sa.imagePullSecrets }}
imagePullSecrets:
    {{- toYaml $sa.imagePullSecrets | nindent 2 }}
  {{- end }}
  {{- if $sa.secrets }}
secrets:
    {{- toYaml $sa.secrets | nindent 2 }}
  {{- end }}
{{- end }}
