{{- if .Values.service }}
  {{- $svc := .Values.service }}
  {{- $name := $svc.name | default $.Release.Name | trunc 63 | trimSuffix "-" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
  {{- include "helpers.app.labels" $ | nindent 4 }}
  {{- with $svc.labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  {{- $annots := include "helpers.app.defaultAnnotations" $ | trim }}
  {{- if or $annots $svc.annotations }}
  annotations:
    {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
    {{- with $svc.annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  {{- end }}
spec:
  {{- if not (empty $svc.clusterIP) }}
  clusterIP: {{ $svc.clusterIP }}
  {{- end }}
  {{- if not (empty $svc.type) }}
  type: {{ $svc.type }}
    {{- if eq $svc.type "ExternalName" }}
      {{- with $svc.externalName }}
  externalName: {{ . }}
      {{- end }}
    {{- else if eq $svc.type "LoadBalancer" }}
      {{- if not (empty $svc.loadBalancerIP) }}
  loadBalancerIP: {{ $svc.loadBalancerIP }}
      {{- end }}
      {{- if not (empty $svc.loadBalancerClass) }}
  loadBalancerClass: {{ $svc.loadBalancerClass }}
      {{- end }}
      {{- if hasKey $svc "allocateLoadBalancerNodePorts" }}
  allocateLoadBalancerNodePorts: {{ $svc.allocateLoadBalancerNodePorts }}
      {{- end }}
      {{- with $svc.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
      {{- end }}
      {{- if $svc.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
        {{- toYaml $svc.loadBalancerSourceRanges | nindent 4 }}
      {{- end }}
    {{- else if (eq $svc.type "NodePort") }}
      {{- with $svc.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
      {{- end }}
      {{- if not (empty $svc.healthCheckNodePort) }}
  healthCheckNodePort: {{ $svc.healthCheckNodePort }}
      {{- end }}
    {{- end }}
    {{- if hasKey $svc "publishNotReadyAddresses" }}
  publishNotReadyAddresses: {{ $svc.publishNotReadyAddresses }}
    {{- end }}
    {{- with $svc.sessionAffinity }}
  sessionAffinity: {{ . }}
    {{- end }}
    {{- with $svc.sessionAffinityConfig }}
  sessionAffinityConfig:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $svc.ipFamilies }}
  ipFamilies:
      {{- toYaml $svc.ipFamilies | nindent 4 }}
    {{- end }}
    {{- with $svc.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
    {{- end }}
    {{- if $svc.externalIPs }}
  externalIPs: {{- toYaml $svc.externalIPs | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if $svc.ports }}
  ports:
    {{- range $svc.ports }}
    - name: {{ .name | default $name }}
      protocol: {{ .protocol | default "TCP" }}
      port: {{ .port }}
      {{- if not (empty .targetPort) }}
      targetPort: {{ .targetPort }}
      {{- end }}
      {{- if not (empty .nodePort) }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if ne ($svc.type | default "") "ExternalName" }}
  selector:
    {{- if $svc.selector }}
      {{- include "helpers.tplvalues.render" (dict "value" $svc.selector "context" $) | nindent 4 }}
    {{- else }}
      {{- include "helpers.app.workloadSelectorLabels" (dict "name" $name "context" $) | nindent 4 }}
      {{- with $svc.extraSelectorLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- end }}
  {{- end }}
{{- end }}
