{{- range $name, $s := $.Values.services }}
  {{- if not ($s.disabled | default false) }}
    {{- $workloadName := $s.workload | default $name }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- $annots := include "helpers.app.defaultAnnotations" $ | trim }}
    {{- if or $annots .annotations }}
  annotations:
      {{- if $annots }}{{ $annots | nindent 4 }}{{- end }}
      {{- with .annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- end }}
spec:
    {{- if not (empty .clusterIP ) }}
  clusterIP: {{ .clusterIP }}
    {{- end }}
    {{- if not (empty .type) }}
  type: {{ .type }}
      {{- if eq .type "ExternalName" }}
        {{- with .externalName }}
  externalName: {{ . }}
        {{- end }}
      {{- else if eq .type "LoadBalancer" }}
        {{- if not (empty .loadBalancerIP) }}
  loadBalancerIP: {{ .loadBalancerIP }}
        {{- end }}
        {{- if not (empty .loadBalancerClass) }}
  loadBalancerClass: {{ .loadBalancerClass }}
        {{- end }}
        {{- if hasKey $s "allocateLoadBalancerNodePorts" }}
  allocateLoadBalancerNodePorts: {{ $s.allocateLoadBalancerNodePorts }}
        {{- end }}
        {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
        {{- end }}
        {{- if .loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
          {{- toYaml .loadBalancerSourceRanges | nindent 4 }}
        {{- end }}
      {{- else if (eq .type "NodePort") }}
        {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
        {{- end }}
        {{- if not (empty .healthCheckNodePort) }}
  healthCheckNodePort: {{ .healthCheckNodePort }}
        {{- end }}
      {{- end }}
      {{- if hasKey $s "publishNotReadyAddresses" }}
  publishNotReadyAddresses: {{ $s.publishNotReadyAddresses }}
      {{- end }}
      {{- with $s.sessionAffinity }}
  sessionAffinity: {{ . }}
      {{- end }}
      {{- with $s.sessionAffinityConfig }}
  sessionAffinityConfig:
        {{- toYaml . | nindent 4 }}
      {{- end }}
      {{- if $s.ipFamilies }}
  ipFamilies:
        {{- toYaml $s.ipFamilies | nindent 4 }}
      {{- end }}
      {{- with $s.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
      {{- end }}
      {{- if .externalIPs }}
  externalIPs: {{- toYaml .externalIPs | nindent 4 }}
      {{- end }}
    {{- end }}
    {{- if $s.ports }}
  ports:
      {{- range $s.ports }}
  - name: {{ .name | default $name}}
    protocol: {{ .protocol | default "TCP"}}
    port: {{ .port }}
        {{- if not (empty .targetPort) }}
    targetPort: {{ .targetPort }}
        {{- end }}
        {{- if not (empty .nodePort) }}
    nodePort: {{ .nodePort }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- if ne ($s.type | default "") "ExternalName" }}
  selector:
      {{- if $s.selector }}
        {{- include "helpers.tplvalues.render" (dict "value" $s.selector "context" $) | nindent 4 }}
      {{- else }}
        {{- include "helpers.app.workloadSelectorLabels" (dict "name" $workloadName "context" $) | nindent 4 }}
        {{- with $s.extraSelectorLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
